// <auto-generated />
namespace Biblioteka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class book_borrow_fix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(book_borrow_fix));
        
        string IMigrationMetadata.Id
        {
            get { return "201812192242095_book_borrow_fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
