// <auto-generated />
namespace Biblioteka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tag_book : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tag_book));
        
        string IMigrationMetadata.Id
        {
            get { return "201811251816578_tag_book"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
