// <auto-generated />
namespace Biblioteka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newBDv4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newBDv4));
        
        string IMigrationMetadata.Id
        {
            get { return "201810271509014_newBDv4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
